# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.twreese.SpoutItemTutorial.SpoutItemTutorial
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  message:
    description: set the greeting message
    usage: /<command> greeting message
    permission: SpoutItemTutorial.message
  changeMe:
    description: gives player new skin
    usage: /<command>
    permission: SpoutItemTutorial.changeMe
  changeMeBack:
    description: returns player's skin
    usage: /<command>
    permission: SpoutItemTutorial.changeMeBack
permissions:
  SpoutItemTutorial.*:
    description: gives all permissions of the plugin commands
    default: true
    children:
      SpoutItemTutorial.message:
        default: true
      SpoutItemTutorial.changeMe:
        default: true
      SpoutItemTutorial.changeMeBack:
        default: true
        